### ISSUE TITLE
Persistency Migration Strategy

### ISSUE THREAD

**Issue by schnedo** [schnedo/therapy_calendar#24]

**Comment by mosauter** [comment]
Not needed really as we don't really have something to migrate from and to. This should only be a talking point if we indeed update the Data-Model *after* the release.

After that I would imagine, some string regexes on the json file will do, after we detect a breaking change. If we really want to prepare for that case, then we should add versioning to the data-model, via a wrapper. Then we should easily be able to detect braking changes when loading from the files and change them accordingly. But music for future ears.
